include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    empty_catches: false
    # non_constant_identifier_names: false
    use_key_in_widget_constructors: false
    # prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_function_literals_in_foreach_calls: false
    prefer_final_fields: false

analyzer:
  errors:
    todo: ignore
    must_be_immutable: ignore