---
name: 功能請求 (繁體中文版)
description: 請求新功能
title: "[Bug]: "
labels: ["Enhancement", "In triage"]
body:
  - type: markdown
    attributes:
      value: |
        感謝您花費您的寶貴時間填寫此表單
  - type: textarea
    id: feature
    attributes:
      label: 描述請求
      description: 請簡單扼要描述您想要的功能
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: 替代方案
      description: 您考慮過的替代方案或方法
  - type: textarea
    id: context 
    attributes:
      label: 額外說明
      description: 關於此功能請求的其他說明或截圖
