name: rpmlauncher
version: 1.0.0.0
version-script: |
  build_id=`git describe --tags --abbrev=0 | sed 's/[0-9]*\.[0-9]*\.[0-9]*\.//'`
  version_id=`git describe --tags --abbrev=0 | sed "s/\.$build_id//"`
  build_id=$(($build_id+1))
  echo $version_id.$build_id
summary: Minecraft Launcher
description: A multi-functional Minecraft Launcher power by The RPMTW Team,Made with Flutter and Dart.
# website: https://www.rpmtw.ga
# source-code: https://github.com/RPMTW/RPMLauncher
# contact: https://discord.gg/5xApZtgV2u
license: GPL-3.0
confinement: strict
base: core18
grade: stable

apps:
  rpmlauncher:
    command: RPMLauncher
    extensions: [flutter-master]
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network-bind
      - unity7

parts:
  rpmlauncher:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - git
      - sed
    override-pull: |
      snapcraftctl pull
      if [ -d "$SNAPCRAFT_PART_BUILD/build" ]
      then
      rm -r $SNAPCRAFT_PART_BUILD/build
      fi
      if [ -d "$SNAPCRAFT_PART_BUILD/linux/flutter/ephemeral" ]
      then
      rm -r $SNAPCRAFT_PART_BUILD/linux/flutter/ephemeral
      fi

    override-build: |
      build_id=`git describe --tags --abbrev=0 | sed 's/[0-9]*\.[0-9]*\.[0-9]*\.//'`
      build_id=$(($build_id+1))
      version_id=`git describe --tags --abbrev=0 | sed "s/\.$build_id//"`
      flutter pub get
      flutter build linux --dart-define="build_id=$build_id" --dart-define="version_type=dev" --dart-define="version=$version_id" --dart-define="sanp=true"
      if [ -d "./build/linux/x64/release/bundle" ] 
      then
      RPM_Path=./build/linux/x64/release/bundle
      else
      RPM_Path=./build/linux/arm64/release/bundle
      fi
      cp $RPM_Path $SNAPCRAFT_PART_INSTALL/bin -r
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/RPMLauncher
