name: rpmlauncher
version: git
summary: Minecraft Launcher
description: A better Minecraft Launcher that supports cross-platform and many functionalities for you to explore!
# website: https://www.rpmtw.com
# source-code: https://github.com/RPMTW/RPMLauncher
# contact: https://discord.gg/5xApZtgV2u
license: GPL-3.0
confinement: strict
base: core22
grade: stable
apps:
  rpmlauncher:
    command: bin/RPMLauncher
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network-bind
      - unity7
      - gsettings
      - opengl

parts:
  rpmlauncher:
    source: .
    source-type: local
    plugin: dump
    build-packages:
      - git
    stage-packages:
      - libgtk-3-dev
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_SRC/RPMLauncher-Linux/RPMLauncher
    override-stage: |
      craftctl default
      chmod +x bin/RPMLauncher
    organize:
      RPMLauncher-Linux: bin/

assumes:
  - snapd2.43
layout:
  "/usr/share/xml/iso-codes":
    bind: "$SNAP/gnome-platform/usr/share/xml/iso-codes"
