name: rpmlauncher
adopt-info: rpmlauncher
summary: Minecraft Launcher
description: A multi-functional Minecraft Launcher power by The RPMTW Team,Made with Flutter and Dart.
# website: https://www.rpmtw.ga
# source-code: https://github.com/RPMTW/RPMLauncher
# contact: https://discord.gg/5xApZtgV2u
license: GPL-3.0
confinement: strict
base: core20
grade: stable
apps:
  rpmlauncher:
    command-chain:
      - snap/command-chain/desktop-launch
    command: bin/RPMLauncher
    plugs:
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network-bind
      - unity7
      - gsettings
      - opengl

parts:
  rpmlauncher:
    source: .
    plugin: dump
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      build_id=`git describe --tags --abbrev=0 | sed 's/[0-9]*\.[0-9]*\.[0-9]*\.//'`
      version_id=`git describe --tags --abbrev=0 | sed "s/\.$build_id//"`
      snapcraftctl set-version "$version_id.$build_id"
    override-build: |
      snapcraftctl build
      chmod +x $SNAPCRAFT_PART_SRC/RPMLauncher-Linux
    organize:
      RPMLauncher-Linux: bin/
  gnome-3-38-extension:
    source: "$SNAPCRAFT_EXTENSIONS_DIR/desktop"
    source-subdir: "gnome"
    plugin: "make"
    make-parameters: ["PLATFORM_PLUG=gnome-3-38-2004"]
    build-packages: ["gcc", "libgtk-3-dev"]

assumes:
  - snapd2.43
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-3-38-2004:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-38-2004
environment:
  SNAP_DESKTOP_RUNTIME: "$SNAP/gnome-platform"
layout:
  "/usr/share/xml/iso-codes":
    bind: "$SNAP/gnome-platform/usr/share/xml/iso-codes"
