name: rpmlauncher_plugin
description: RPMLauncher Plugin
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: RpmlauncherPlugin
      macos:
        pluginClass: RpmlauncherPlugin
      windows:
        pluginClass: RpmlauncherPlugin