name: Pull Request Analyze
on: [pull_request]

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.8.0-10.1.pre
          channel: beta
          cache: true
      - run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze the code
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          fatal-warnings: true
          annotate: true
          annotate-only: false

  Coverage:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.8.0-10.1.pre
          channel: beta
          cache: true
      - name: Generate coverage
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter test --coverage
        shell: bash
        continue-on-error: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  Build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runs-on: ubuntu-latest
            output-path: build/linux/x64/release/bundle
            os-name: linux
          - runs-on: windows-latest
            output-path: build/windows/runner/Release
            os-name: windows
          - runs-on: macos-latest
            output-path: build/macos/Build/Products/Release/rpmlauncher.app
            os-name: macos
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.8.0-10.1.pre
          channel: beta
          cache: true
      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - name: Build for ${{ runner.os }}
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build ${{ matrix.os-name }} --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=debug" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-${{ runner.os }}-debug
          path: ${{ matrix.output-path}}
